apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "d2.fullname" . }}-config
  labels:
    {{- include "d2.labels" . | nindent 4 }}
data:
  adminWhitelist.json: {{ .Values.d2.adminWhitelist | toJson | quote }}
  config.json: {{ .Values.d2.config | toJson | quote }}
  netApiKeys.json: {{ .Values.d2.netApiKeys | toJson | quote }}
  platformTokens.json: {{ .Values.d2.platformTokens | toJson | quote }}
