image: "swift:5.4"

stages:
  - build
  - test
  - deploy

before_script:
  # Workaround, see explanation in Dockerfile
  - "[ -d /usr/lib/python2.7/site-packages ] && mv /usr/lib/python2.7/site-packages /usr/lib/python2.7/dist-packages && ln -s dist-packages /usr/lib/python2.7/site-packages"
  - apt-get update && apt-get install -y software-properties-common && add-apt-repository -y ppa:alex-p/tesseract-ocr
  - apt-get update && apt-get install -y libopus-dev libsodium-dev libcairo2-dev libsqlite3-dev libtesseract-dev libleptonica-dev libgraphviz-dev

build:
  stage: build
  script:
    - swift build -c release
  artifacts:
    paths:
      - ./.build/release/D2
    expire_in: 1 week

test:
  stage: test
  script:
    - swift test -c release

deploy:
  image:
    name: docker/compose:1.24.1
    entrypoint: ["/bin/sh", "-c"]
  stage: deploy
  script:
    - docker-compose build
    - docker-compose up -d
