name: Build

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          swift: '5.7'
        - os: macos-12
          swift: '5.7'

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
      # Workaround for FFI modulemap redefinition error
      # https://github.com/tauri-apps/tauri/issues/1150#issuecomment-768310979
    - name: Remove duplicate FFI includes (macOS)
      if: runner.os == 'macOS'
      run: sudo rm -rf /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/include/ffi
    - name: Install system dependencies (Linux)
      if: runner.os == 'Linux'
      run: sudo Scripts/install-build-dependencies-apt
    - name: Install system dependencies (macOS)
      if: runner.os == 'macOS'
      run: sudo Scripts/install-dependencies-brew
    - name: Install Swift
      uses: fwal/setup-swift@v1
      with:
        swift-version: ${{ matrix.swift }}
    - name: Build
      run: swift build
    - name: Test
      run: swift test
