name: macOS

on: [push]

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies with Homebrew
      run: |
        brew tap vapor/tap
        brew install ctls pkg-config cairo graphviz
    - name: Pick the right Xcode version
      run: sudo xcode-select -s /Applications/Xcode_12.app
    - name: Build
      run: swift build
    - name: Test
      run: swift test

